### ISSUE TITLE
[Compatibility] Trades not changing when using Mrbysco Retraining

### ISSUE THREAD

**Issue by RAK-XTECH** [Ramixin/VisibleTraders#1]
Mrbysco [Retraining](https://github.com/Mrbysco/Retraining) is a mod that allows rerolling the villager trade without having to break the workstation.

Retraining successfully changes the first two trades of a villager, but the preview for the locked trades remains the same no matter how many times the villager is retrained.

Reporting since other mods that have simillar rerolling mechanics probably will probably have the same outcome.

For a suggestion on how to fix, save the first two trades, and if they aren't the same anymore for whatever reason then all the locked trades get a new roll.

**Comment by Ramixin** [comment]
Fixed as of future version 0.0.4
