### ISSUE TITLE
Crash [1.20.1 Fabric 0.0.3]

### ISSUE THREAD

**Issue by DoloSaber** [Ramixin/VisibleTraders#10]
Hi, Thank you for your reply, I forgot to upload it before. The game still crashing in 0.0.3, When you right click on a villager.
https://mclo.gs/ogPcy1b

**Comment by Ramixin** [comment]
Thank you @DoloSaber, this is the same issue as before. V:0.0.3 will now only support 1.20.5+

**Comment by DoloSaber** [comment]
> Thank you @DoloSaber, this is the same issue as before. V:0.0.3 will now only support 1.20.5+
Is there will be support 1.20.1 Fabric in the future？

**Comment by Ramixin** [comment]
I will create a 1.20-1.20.4 version of the mod soon. It will either be for V:0.0.4 or V:0.0.5 depending if compatibility with Easy Traders is viable
