### ISSUE TITLE
Some villagers not unlocking trades

### ISSUE THREAD

**Issue by Proxi2** [Ramixin/VisibleTraders#3]
I'm having this bug where if I find a villager that only shows the first 2 trades and not any of the locked ones like it should (after closing and opening the trade ui several times to make sure it had a chance to generate), no matter how much you trade and no matter how much it levels up, it won't ever offer any more trades. It doesn't happen to all villagers (though there is a higher number of bugged villagers than working ones), and it doesn't appear to happen if I only use the Visible Traders mod. For the life of me I can't figure out what the conflict is. This doesn't happen if I take Visible Traders out of the modpack

Here's some logs:
https://mclo.gs/YIxuJDv

![image](https://github.com/user-attachments/assets/0e83067b-c2e8-43e1-9bdf-a0f072d5944d)
![image](https://github.com/user-attachments/assets/fd03a1b9-7295-490e-9f9f-030f5c08821d)

For those logs all I did was make a new world, spawn villagers and place composters, took screenshots of the villagers trade ui, then left. I will say that's the first time I've ever seen only the next 2 trades showing usually it shows all of them

**Comment by Proxi2** [comment]
I would also like to add that I just removed the mod and readded it, and it still has the same problem, but will properly apply the trades to the existing villagers from before which fixes them

**Comment by Ramixin** [comment]
thank you for the report @Proxi2. As I look into this, could you help by telling me what gets outputted when you run this command close to the villager? `/data get entity @e[type=minecraft:villager,sort=nearest,limit=1] LockedOffers`

**Comment by Ramixin** [comment]
Fixed as of 0.0.4. If this error returns, feel free to reopen this issue if possible or start a new one.

**Comment by Proxi2** [comment]
Very sorry I didn’t respond to your comment from a week ago. GitHub didn’t send me any emails about this issue until now. I’ll give the new update a try. Your work to fix it is greatly appreciated and my server mates will be happy to hear that it’ll be readded. Thank you!
