### ISSUE TITLE
[question] I assume that the item preview only works after you lock the villager in a trade? 

### ISSUE THREAD

**Issue by ffuentesm** [Ramixin/VisibleTraders#5]
I assume you can only preview the future trades after you trade with the villager at least once, right? 
As the UI of villagers I have not traded yet is like this. 
![image](https://github.com/user-attachments/assets/fce29040-372c-416b-ae9d-cbb9bb1c93b4)

**Comment by Ramixin** [comment]
Hello @ffuentesm. The trades should be automatically generated even if you haven't traded with the villager yet. Could you please send me one of your logs in which Visible traders was in use? (please use https://mclo.gs) I have been having issues lately with trade generation with custom villager trades

**Comment by Ramixin** [comment]
@ffuentesm, after further look into Easy Villagers and how it works, the trades are not generating since the villager is not being updated the same inside the block as outside. This is an incompatibility on their end and can not be fixed here
